robot_cameras:
  floor_robot_camera: 
    # active: true
    active: false
    type: rgb
  
  ceiling_robot_camera: 
    # active: true
    active: false
    type: rgbd

static_sensors:
  right_bins_camera:
    type: advanced_logical_camera
    visualize_fov: true
    pose:
      xyz: [-2.286, 2.96, 1.8]
      rpy: [pi, pi/2, 0]

  left_bins_camera:
    type: advanced_logical_camera
    visualize_fov: true
    pose:
      xyz: [-2.286, -2.96, 1.8]
      rpy: [pi, pi/2, 0]

  kts1_camera:
    type: advanced_logical_camera
    visualize_fov: true
    pose:
      xyz: [-1.3, -5.8, 1.8]
      rpy: [pi, pi/2, pi/2]
  
  kts2_camera:
    type: advanced_logical_camera
    visualize_fov: true
    pose:
      xyz: [-1.3, 5.8, 1.8]
      rpy: [pi, pi/2, -pi/2]
  
  conveyor_breakbeam:
    type: break_beam
    visualize_fov: true
    pose:
      xyz: [-0.352, 3.91, 0.88]
      rpy: [0, 0, pi]
  
  conveyor_camera:
    type: advanced_logical_camera
    visualize_fov: true
    pose:
      xyz: [-0.573, 3.915, 1.8]
      rpy: [pi/2, pi/2, 0]

  # as1_camera:
  #   type: advanced_logical_camera
  #   visualize_fov: true
  #   pose:
  #     xyz: [0.5, 5.8, 1.8]
  #     rpy: [pi, pi/2, -pi/2]
  
  # as2_camera:
  #   type: advanced_logical_camera
  #   visualize_fov: true
  #   pose:
  #     xyz: [0.5, 5.8, 1.8]
  #     rpy: [pi, pi/2, -pi/2]
  
  # as3_camera:
  #   type: advanced_logical_camera
  #   visualize_fov: true
  #   pose:
  #     xyz: [0.5, 5.8, 1.8]
  #     rpy: [pi, pi/2, -pi/2]
  
  # as4_camera:
  #   type: advanced_logical_camera
  #   visualize_fov: true
  #   pose:
  #     xyz: [0.5, 5.8, 1.8]
  #     rpy: [pi, pi/2, -pi/2]

  agv1_as1_camera:
    type: advanced_logical_camera
    visualize_fov: true
    pose:
      xyz: [-7.673742, 4.786616, 1.8]
      rpy: [pi, pi/2, -pi/2]
  agv1_as2_camera:
    type: advanced_logical_camera
    visualize_fov: true
    pose:
      xyz: [-12.691347, 4.786616, 1.8]
      rpy: [pi, pi/2, -pi/2]
  agv2_as1_camera:
    type: advanced_logical_camera
    visualize_fov: true
    pose:
      xyz: [-7.673742, 1.197786, 1.8]
      rpy: [pi, pi/2, -pi/2]
  agv2_as2_camera:
    type: advanced_logical_camera
    visualize_fov: true
    pose:
      xyz: [-12.691347, 1.197786, 1.8]
      rpy: [pi, pi/2, -pi/2]
  agv3_as3_camera:
    type: advanced_logical_camera
    visualize_fov: true
    pose:
      xyz: [-7.673742, -1.197786, 1.8]
      rpy: [pi, pi/2, -pi/2]
  agv3_as4_camera:
    type: advanced_logical_camera
    visualize_fov: true
    pose:
      xyz: [-12.691347, -1.197786, 1.8]
      rpy: [pi, pi/2, -pi/2]
  agv4_as3_camera:
    type: advanced_logical_camera
    visualize_fov: true
    pose:
      xyz: [-7.673742, -4.786616, 1.8]
      rpy: [pi, pi/2, -pi/2]
  agv4_as4_camera:
    type: advanced_logical_camera
    visualize_fov: true
    pose:
      xyz: [-12.691347, -4.786616, 1.8]
      rpy: [pi, pi/2, -pi/2]

    