#!/usr/bin/env bash
# ros2 launch ariac_gazebo ariac.launch.py \
#  dev_mode:=true \
#  ;


ros2 launch ariac_gazebo ariac.launch.py \
 dev_mode:=true \
 competitor_pkg:=smallcat \
 sensor_config:=sensors \
 ;


 
#  trial_name:=<> \
#  competitor_pkg:=<> \
#  sensor_config:=<> \
#  record_state:=true
